# -*- coding: utf-8 -*-
"""Assignment Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o46iYgX-4bX-RqHCcgl9G8lUOSe0106f

Question 1
"""

def lengthCalulator(word1,word2):
    return len(word1) + len(word2)
#take input from user
first_name = input("")
last_name = input("")
#calculate total letters in first and last name
total_letters = lengthCalulator(first_name,last_name)
#convert first name and last name to upper case
first_name = first_name.upper()
last_name = last_name.upper()

print(f"First name (upper): {first_name}")
print(f"Last name (lower): {last_name}")
print("Sum of letters in your first and last name:", total_letters)

"""Question 2"""

def area_of_circle(radius):
    return 3.14 * radius**2
def area_of_rectangle(length,width):
    return length * width
def area_of_square(side):
    return side**2
def area_of_triangle(base,height):
    return 0.5 * base * height

# Display options for shapes
print("Calculate the area of following shapes:")
print("1. Circle")
print("2. Rectangle")
print("3. Square")
print("4. Triangle")

while True:
    # Take user input for shape selection
    shape = int(input("Enter the number of the shape: "))

    # Calculate and print the area based on the selected shape
    if shape == 1:
        radius = float(input("Enter the radius of the circle: "))
        print("Area of the circle is:", area_of_circle(radius))
    elif shape == 2:
        length = float(input("Enter the length of the rectangle: "))
        width = float(input("Enter the width of the rectangle: "))
        print("Area of the rectangle is:", area_of_rectangle(length, width))
    elif shape == 3:
        side = float(input("Enter the side of the square: "))
        print("Area of the square is:", area_of_square(side))
    elif shape == 4:
        base = float(input("Enter the base of the triangle: "))
        height = float(input("Enter the height of the triangle: "))
        print("Area of the triangle is:", area_of_triangle(base, height))
    else:
        print("Invalid input")
        break

"""Task 3"""

import random
colors = ["red", "blue", "green", "yellow", "orange", "purple"]
index = random.randint(0, len(colors) - 1)
selected_color = colors[index]
password = selected_color[::-1]
print("Selected Color:", selected_color)
print("Generated Password:", password)

