# -*- coding: utf-8 -*-
"""Classwork Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBuTRSp_PhzMvoazDjpPr4kAmE-1nXiV

Class Work
"""

# Indentation
if True:
  print("This is my second class of Python language")

# comments
# if True: ctrl + /

# Variables and constants
name = 'asddfesdfsd'
age = 22256

PI = 3.14159 # constant (capital)

print ("My name is", name)
print ("My age is", age)
print (PI)

# Input and output function
name = input ("Enter your name: ") # input function
print ("My name is", name) # output function

print (type(name))

# Primitive data type
x = 10 # integer
y = 10.01 # float
z = 4 +3j # imaginary

print ("Real number is", z.real)
print ("Imaginary number is", z.imag)

# String

sentence = "This is my second class of Python language"
print ("First letter:", sentence[0])
print ("Here is:", sentence[-15])


greeting = "Python" + "language"
print (greeting)


repeat = "Python" * 3
print (repeat)


print("Sliced string:", sentence[0:4])
print("Sliced string:", sentence[0:23])


print ("Lower case:", sentence.lower())
print ("Upper case:", sentence.upper())


print ("replace:", sentence.replace("Python", "C++"))

# Collect Data Types

# List
numbers = [1, 2, 3, 4, 5]

numbers.append(6)
print (numbers)

# List slicing
numbers[:3] # 0, 1, 2

# Tuple
numbers = (1, 2, 3, 4, 5)

print (numbers)
print (numbers[:3])

# Sets
numbers = {1, 2, 3, 4, 5}

numbers.add(5)

print (numbers)

# Dictionary
student = {"name": "random"} # key value pair

student["name"] = "secondRandom"
print (student)

student["age"] = 22
print(student)

# Implicit Conversion
a = 10
b = 2.3

sum = a + b
print(sum)

print(type(sum))

# Explicit Conversion
age = "22"
integer = 11

age = int(age)
# integer = str(integer)
# float(age)

print (type(age))

result = age + integer
print (result)

# Arithmetic Operators

num1 = 10
num2 = 4

print("Addition:", num1 + num2)
print("Subtraction:", num1 - num2)
print("Multiplication:", num1 * num2)
print("Division:", num1 / num2)
print("Floor_Division:", num1 // num2)
print("Remainder:", num1 % num2)
print("Modulus:", num1 % num2)
print("Exponent:", num1 ** num2) #power

# Comparison Operators

print("Equal:", num1 == num2)
print("Not equal:", num1 != num2)
print("Greater then:", num1 > num2)
print("Less than:", num1 < num2)

# Logical Operators

a = True
b = False

print("a AND b:", a and b)
print("a OR b:", a or b)
print("a NOT b:", not b)

# Assignment Operators

a = 10
a += 5 # a = a + 5
a -= 5 # a = a - 5
a *= 5 # a = a * 5
a /= 5 # a = a / 5

print(a)

# Length Function

sentence = "A bunch of words"

print (len(sentence))

# Split Function

sentence = "A: bunch: of: words"

print (sentence.split(':'))

# Random Function

import random

print(random.randint(1, 10))
print(random.random())

items = ['item1', 'item2', 'item3']
print(random.choice(items))